# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'check_update.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_check_update(object):
    def setupUi(self, check_update):
        check_update.setObjectName("check_update")
        check_update.resize(600, 400)
        check_update.setMinimumSize(QtCore.QSize(600, 400))
        check_update.setMaximumSize(QtCore.QSize(1200, 800))
        self.centralwidget = QtWidgets.QWidget(check_update)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.update_text = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_text.sizePolicy().hasHeightForWidth())
        self.update_text.setSizePolicy(sizePolicy)
        self.update_text.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.update_text.setObjectName("update_text")
        self.verticalLayout.addWidget(self.update_text, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.verticalLayout, 4, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 5, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(150, -1, 150, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.current_data_verison = QtWidgets.QLabel(self.centralwidget)
        self.current_data_verison.setObjectName("current_data_verison")
        self.gridLayout.addWidget(self.current_data_verison, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.current_program_version = QtWidgets.QLabel(self.centralwidget)
        self.current_program_version.setObjectName("current_program_version")
        self.gridLayout.addWidget(self.current_program_version, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.latest_program_version = QtWidgets.QLabel(self.centralwidget)
        self.latest_program_version.setObjectName("latest_program_version")
        self.gridLayout.addWidget(self.latest_program_version, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.latest_data_version = QtWidgets.QLabel(self.centralwidget)
        self.latest_data_version.setObjectName("latest_data_version")
        self.gridLayout.addWidget(self.latest_data_version, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.gridLayout, 3, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_2.setRowStretch(0, 2)
        self.gridLayout_2.setRowStretch(3, 3)
        self.gridLayout_2.setRowStretch(4, 1)
        self.gridLayout_2.setRowStretch(5, 2)
        check_update.setCentralWidget(self.centralwidget)

        self.retranslateUi(check_update)
        QtCore.QMetaObject.connectSlotsByName(check_update)

    def retranslateUi(self, check_update):
        _translate = QtCore.QCoreApplication.translate
        check_update.setWindowTitle(_translate("check_update", "关于 - 猴面雀"))
        self.update_text.setText(_translate("check_update", "TextLabel"))
        self.label_8.setText(_translate("check_update", "<html><head/><body><p align=\"center\">本程序源码使用LGPL 2.1 协议开源发布在<a href=\"https://github.com/NagaResst/Paissa\"><span style=\" text-decoration: underline; color:#0000ff;\">github</span></a>，任何人都可以免费使用。</p><p align=\"center\">如您购买获得本工具，请举报并退款。如果您觉得猴面雀很好用，请分享给其他人。</p></body></html>"))
        self.label_2.setText(_translate("check_update", "主程序版本"))
        self.current_data_verison.setText(_translate("check_update", "TextLabel"))
        self.label_6.setText(_translate("check_update", "当前版本"))
        self.label_3.setText(_translate("check_update", "数据版本"))
        self.current_program_version.setText(_translate("check_update", "TextLabel"))
        self.latest_program_version.setText(_translate("check_update", "N/A"))
        self.label_10.setText(_translate("check_update", "最新版本"))
        self.latest_data_version.setText(_translate("check_update", "N/A"))
        self.label_7.setText(_translate("check_update", "<html><head/><body><p align=\"center\">猴面雀 - FF14国服市场价格查询，成本计算小工具</p><p align=\"center\">夕山菀 @ 紫水栈桥  </p></body></html>"))
