# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loading_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_load_page(object):
    def setupUi(self, load_page):
        load_page.setObjectName("load_page")
        load_page.resize(601, 467)
        self.gridLayout_2 = QtWidgets.QGridLayout(load_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.loading_text = QtWidgets.QLabel(load_page)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.loading_text.setFont(font)
        self.loading_text.setObjectName("loading_text")
        self.gridLayout_2.addWidget(self.loading_text, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)

        self.retranslateUi(load_page)
        QtCore.QMetaObject.connectSlotsByName(load_page)

    def retranslateUi(self, load_page):
        _translate = QtCore.QCoreApplication.translate
        load_page.setWindowTitle(_translate("load_page", "Frame"))
        self.loading_text.setText(_translate("load_page", "查询中。。。"))
