# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'query_item_id.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_query_item_id(object):
    def setupUi(self, query_item_id):
        query_item_id.setObjectName("query_item_id")
        query_item_id.resize(1081, 683)
        self.gridLayout = QtWidgets.QGridLayout(query_item_id)
        self.gridLayout.setObjectName("gridLayout")
        self.query_index_page = QtWidgets.QWidget(query_item_id)
        self.query_index_page.setEnabled(True)
        self.query_index_page.setMouseTracking(False)
        self.query_index_page.setAutoFillBackground(False)
        self.query_index_page.setObjectName("query_index_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.query_index_page)
        self.gridLayout_2.setContentsMargins(100, 100, 100, 200)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.query_box = QtWidgets.QVBoxLayout()
        self.query_box.setContentsMargins(-1, 0, -1, 0)
        self.query_box.setObjectName("query_box")
        self.query_is_hq = QtWidgets.QCheckBox(self.query_index_page)
        self.query_is_hq.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.query_is_hq.setFont(font)
        self.query_is_hq.setIconSize(QtCore.QSize(20, 20))
        self.query_is_hq.setObjectName("query_is_hq")
        self.query_box.addWidget(self.query_is_hq, 0, QtCore.Qt.AlignRight)
        self.input_item_name = QtWidgets.QLineEdit(self.query_index_page)
        self.input_item_name.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.input_item_name.setFont(font)
        self.input_item_name.setText("")
        self.input_item_name.setObjectName("input_item_name")
        self.query_box.addWidget(self.input_item_name)
        self.query_button = QtWidgets.QToolButton(self.query_index_page)
        self.query_button.setMinimumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.query_button.setFont(font)
        self.query_button.setObjectName("query_button")
        self.query_box.addWidget(self.query_button, 0, QtCore.Qt.AlignRight)
        self.gridLayout_2.addLayout(self.query_box, 0, 0, 1, 1)
        self.gridLayout_2.setRowStretch(0, 2)
        self.gridLayout.addWidget(self.query_index_page, 0, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 1)

        self.retranslateUi(query_item_id)
        QtCore.QMetaObject.connectSlotsByName(query_item_id)

    def retranslateUi(self, query_item_id):
        _translate = QtCore.QCoreApplication.translate
        query_item_id.setWindowTitle(_translate("query_item_id", "Frame"))
        self.query_is_hq.setText(_translate("query_item_id", "查询HQ"))
        self.input_item_name.setPlaceholderText(_translate("query_item_id", "请输入要查询的物品名称"))
        self.query_button.setText(_translate("query_item_id", "查询"))
