# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'query_item_id.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_query_item_id(object):
    def setupUi(self, query_item_id):
        query_item_id.setObjectName("query_item_id")
        query_item_id.resize(638, 473)
        self.verticalLayout = QtWidgets.QVBoxLayout(query_item_id)
        self.verticalLayout.setObjectName("verticalLayout")
        self.query_box = QtWidgets.QVBoxLayout()
        self.query_box.setContentsMargins(80, 0, 80, 0)
        self.query_box.setObjectName("query_box")
        self.query_is_hq = QtWidgets.QCheckBox(query_item_id)
        self.query_is_hq.setMinimumSize(QtCore.QSize(15, 15))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.query_is_hq.setFont(font)
        self.query_is_hq.setIconSize(QtCore.QSize(20, 20))
        self.query_is_hq.setObjectName("query_is_hq")
        self.query_box.addWidget(self.query_is_hq, 0, QtCore.Qt.AlignRight)
        self.input_item_name = QtWidgets.QLineEdit(query_item_id)
        self.input_item_name.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.input_item_name.setFont(font)
        self.input_item_name.setText("")
        self.input_item_name.setClearButtonEnabled(False)
        self.input_item_name.setObjectName("input_item_name")
        self.query_box.addWidget(self.input_item_name)
        self.query_button = QtWidgets.QToolButton(query_item_id)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.query_button.sizePolicy().hasHeightForWidth())
        self.query_button.setSizePolicy(sizePolicy)
        self.query_button.setMinimumSize(QtCore.QSize(120, 40))
        self.query_button.setMaximumSize(QtCore.QSize(240, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.query_button.setFont(font)
        self.query_button.setObjectName("query_button")
        self.query_box.addWidget(self.query_button, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.query_box)

        self.retranslateUi(query_item_id)
        QtCore.QMetaObject.connectSlotsByName(query_item_id)

    def retranslateUi(self, query_item_id):
        _translate = QtCore.QCoreApplication.translate
        query_item_id.setWindowTitle(_translate("query_item_id", "Form"))
        self.query_is_hq.setText(_translate("query_item_id", "查询HQ"))
        self.input_item_name.setPlaceholderText(_translate("query_item_id", "请输入要查询的物品名称"))
        self.query_button.setText(_translate("query_item_id", "查询"))
