# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cost_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cost_page(object):
    def setupUi(self, cost_page):
        cost_page.setObjectName("cost_page")
        cost_page.resize(1069, 808)
        self.gridLayout = QtWidgets.QGridLayout(cost_page)
        self.gridLayout.setObjectName("gridLayout")
        self.cost_tree = QtWidgets.QTreeWidget(cost_page)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.cost_tree.setFont(font)
        self.cost_tree.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.cost_tree.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.cost_tree.setObjectName("cost_tree")
        self.cost_tree.headerItem().setText(0, "材料")
        self.gridLayout.addWidget(self.cost_tree, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.profit_text = QtWidgets.QLabel(cost_page)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.profit_text.setFont(font)
        self.profit_text.setObjectName("profit_text")
        self.horizontalLayout.addWidget(self.profit_text, 0, QtCore.Qt.AlignRight)
        self.profit = QtWidgets.QLabel(cost_page)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.profit.setFont(font)
        self.profit.setObjectName("profit")
        self.horizontalLayout.addWidget(self.profit, 0, QtCore.Qt.AlignLeft)
        self.d_cost_text = QtWidgets.QLabel(cost_page)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.d_cost_text.setFont(font)
        self.d_cost_text.setObjectName("d_cost_text")
        self.horizontalLayout.addWidget(self.d_cost_text, 0, QtCore.Qt.AlignRight)
        self.d_cost = QtWidgets.QLabel(cost_page)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.d_cost.setFont(font)
        self.d_cost.setObjectName("d_cost")
        self.horizontalLayout.addWidget(self.d_cost)
        self.o_cost_text = QtWidgets.QLabel(cost_page)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.o_cost_text.setFont(font)
        self.o_cost_text.setObjectName("o_cost_text")
        self.horizontalLayout.addWidget(self.o_cost_text, 0, QtCore.Qt.AlignRight)
        self.o_cost = QtWidgets.QLabel(cost_page)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.o_cost.setFont(font)
        self.o_cost.setObjectName("o_cost")
        self.horizontalLayout.addWidget(self.o_cost)
        self.click_c = QtWidgets.QPushButton(cost_page)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.click_c.setFont(font)
        self.click_c.setObjectName("click_c")
        self.horizontalLayout.addWidget(self.click_c, 0, QtCore.Qt.AlignRight)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(cost_page)
        QtCore.QMetaObject.connectSlotsByName(cost_page)

    def retranslateUi(self, cost_page):
        _translate = QtCore.QCoreApplication.translate
        cost_page.setWindowTitle(_translate("cost_page", "Frame"))
        self.cost_tree.headerItem().setText(1, _translate("cost_page", "理想单价"))
        self.cost_tree.headerItem().setText(2, _translate("cost_page", "所需数量"))
        self.cost_tree.headerItem().setText(3, _translate("cost_page", "该项成本"))
        self.cost_tree.headerItem().setText(4, _translate("cost_page", "最佳服务器"))
        self.profit_text.setText(_translate("cost_page", "估算的利润空间："))
        self.profit.setText(_translate("cost_page", "N/A"))
        self.d_cost_text.setText(_translate("cost_page", "直接材料成本："))
        self.d_cost.setText(_translate("cost_page", "N/A"))
        self.o_cost_text.setText(_translate("cost_page", "原始材料成本："))
        self.o_cost.setText(_translate("cost_page", "N/A"))
        self.click_c.setText(_translate("cost_page", "复制"))
