# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_history_Window(object):
    def setupUi(self, history_Window):
        history_Window.setObjectName("history_Window")
        history_Window.setWindowModality(QtCore.Qt.NonModal)
        history_Window.resize(200, 600)
        history_Window.setMinimumSize(QtCore.QSize(200, 600))
        history_Window.setMaximumSize(QtCore.QSize(400, 900))
        history_Window.setIconSize(QtCore.QSize(0, 0))
        history_Window.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.centralwidget = QtWidgets.QWidget(history_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.history_list = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.history_list.setFont(font)
        self.history_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.history_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.history_list.setObjectName("history_list")
        self.gridLayout.addWidget(self.history_list, 0, 0, 1, 1)
        history_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(history_Window)
        QtCore.QMetaObject.connectSlotsByName(history_Window)

    def retranslateUi(self, history_Window):
        _translate = QtCore.QCoreApplication.translate
        history_Window.setWindowTitle(_translate("history_Window", "历史查询"))
        self.history_list.setSortingEnabled(False)
